services:
    acme_csvcleanerconnector.processor.denormalization.product.flat:
        class: '%pim_connector.processor.denormalization.product.class%'
        arguments:
            - '@acme_csvcleanerconnector.array_converter.flat.product'
            - '@pim_catalog.repository.product'
            - '@pim_catalog.builder.product'
            - '@pim_catalog.updater.product'
            - '@pim_catalog.validator.product'
            - '@akeneo_storage_utils.doctrine.object_detacher'
            - '@pim_catalog.comparator.filter.product'
