language: python
python:
  - "2.7"

sudo: false
cache: pip

# command to install dependencies
install: "pip install sphinx~=1.5.3 git+https://github.com/fabpot/sphinx-php.git git+https://github.com/mickaelandrieu/sphinxcontrib.youtube.git"

# command to run tests
script: sphinx-build -nWT -b dummy . _build/html
# Flags used here, not in `make html`:
#  -n   Run in nit-picky mode. Currently, this generates warnings for all missing references.
#  -W   Turn warnings into errors. This means that the build stops at the first warning and sphinx-build exits with exit status 1.
#  -T   Display the full traceback when an unhandled exception occurs.
#  -b   Use `dummy` builder doesn't write files on filesystem.
