# Resources/config/requirejs.yml

config:
    paths:
        "%THE_NAME_OF_YOUR_FECTHER%" : "%the_path_of_your_fetcher%" #For example -> mycustomfetcher: mycustombundle/js/my-custom-choices-list
    config:
        pim/fetcher-registry:
            fetchers:
                "%THE_NAME_OF_YOUR_FECTHER%":
                    module: pim/base-fetcher
                    options:
                        urls:
                            list: "%the_route_name_of_your_controller_action%"
